# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b41a1fc58122338fe674fa1d7261923d"
name = "draft-editor"
handle = "draft-edit"
application_url = "https://forestry-trust-fluid-strip.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,write_draft_orders,read_customers,read_products"

[auth]
redirect_urls = [ "https://forestry-trust-fluid-strip.trycloudflare.com/api/auth" ]
